language: scala
sudo: true
services:
  - docker
scala:
  - 2.12.8
  - 2.13.0
jdk:
  - openjdk8
  - openjdk11
script:
  - "./scripts/launch-all.sh"
  - docker ps -a
  - "./build.sh"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot
   - $HOME/.sbt/launchers
   - $HOME/.cache/coursier
   - $HOME/.jabba/jdk
